version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      day: 'tuesday'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 5
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
  - package-ecosystem: 'gomod'
    directory: '/deploy/tools'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 3
  - package-ecosystem: 'gomod'
    directory: '/internal/metrics/tools'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
    open-pull-requests-limit: 3
