version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: "23:17"
    labels:
    - "dependencies"
    - "auto-merge"
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: "23:17"
    open-pull-requests-limit: 5
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
    labels:
    - "dependencies"
    - "auto-merge"
  - package-ecosystem: 'gomod'
    directory: '/deploy/tools'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: "23:17"
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "auto-merge"
  - package-ecosystem: 'gomod'
    directory: '/internal/metrics/tools'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: "23:17"
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "auto-merge"
